/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	neutronv1 "github.com/kubeovn/kube-ovn/pkg/neutron/apis/neutron/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFips implements FipInterface
type FakeFips struct {
	Fake *FakeKubeovnV1
}

var fipsResource = schema.GroupVersionResource{Group: "kubeovn.io", Version: "v1", Resource: "fips"}

var fipsKind = schema.GroupVersionKind{Group: "kubeovn.io", Version: "v1", Kind: "Fip"}

// Get takes name of the fip, and returns the corresponding fip object, and an error if there is any.
func (c *FakeFips) Get(ctx context.Context, name string, options v1.GetOptions) (result *neutronv1.Fip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(fipsResource, name), &neutronv1.Fip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*neutronv1.Fip), err
}

// List takes label and field selectors, and returns the list of Fips that match those selectors.
func (c *FakeFips) List(ctx context.Context, opts v1.ListOptions) (result *neutronv1.FipList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(fipsResource, fipsKind, opts), &neutronv1.FipList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &neutronv1.FipList{ListMeta: obj.(*neutronv1.FipList).ListMeta}
	for _, item := range obj.(*neutronv1.FipList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fips.
func (c *FakeFips) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(fipsResource, opts))
}

// Create takes the representation of a fip and creates it.  Returns the server's representation of the fip, and an error, if there is any.
func (c *FakeFips) Create(ctx context.Context, fip *neutronv1.Fip, opts v1.CreateOptions) (result *neutronv1.Fip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(fipsResource, fip), &neutronv1.Fip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*neutronv1.Fip), err
}

// Update takes the representation of a fip and updates it. Returns the server's representation of the fip, and an error, if there is any.
func (c *FakeFips) Update(ctx context.Context, fip *neutronv1.Fip, opts v1.UpdateOptions) (result *neutronv1.Fip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(fipsResource, fip), &neutronv1.Fip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*neutronv1.Fip), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFips) UpdateStatus(ctx context.Context, fip *neutronv1.Fip, opts v1.UpdateOptions) (*neutronv1.Fip, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(fipsResource, "status", fip), &neutronv1.Fip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*neutronv1.Fip), err
}

// Delete takes name of the fip and deletes it. Returns an error if one occurs.
func (c *FakeFips) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(fipsResource, name), &neutronv1.Fip{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFips) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(fipsResource, listOpts)

	_, err := c.Fake.Invokes(action, &neutronv1.FipList{})
	return err
}

// Patch applies the patch and returns the patched fip.
func (c *FakeFips) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *neutronv1.Fip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(fipsResource, name, pt, data, subresources...), &neutronv1.Fip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*neutronv1.Fip), err
}
