/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubeovn/kube-ovn/pkg/neutron/apis/neutron/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FipLister helps list Fips.
// All objects returned here must be treated as read-only.
type FipLister interface {
	// List lists all Fips in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Fip, err error)
	// Get retrieves the Fip from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Fip, error)
	FipListerExpansion
}

// fipLister implements the FipLister interface.
type fipLister struct {
	indexer cache.Indexer
}

// NewFipLister returns a new FipLister.
func NewFipLister(indexer cache.Indexer) FipLister {
	return &fipLister{indexer: indexer}
}

// List lists all Fips in the indexer.
func (s *fipLister) List(selector labels.Selector) (ret []*v1.Fip, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Fip))
	})
	return ret, err
}

// Get retrieves the Fip from the index for a given name.
func (s *fipLister) Get(name string) (*v1.Fip, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("fip"), name)
	}
	return obj.(*v1.Fip), nil
}
