/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kubeovn/kube-ovn/pkg/neutron/apis/neutron/v1"
	scheme "github.com/kubeovn/kube-ovn/pkg/neutron/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FipsGetter has a method to return a FipInterface.
// A group's client should implement this interface.
type FipsGetter interface {
	Fips() FipInterface
}

// FipInterface has methods to work with Fip resources.
type FipInterface interface {
	Create(ctx context.Context, fip *v1.Fip, opts metav1.CreateOptions) (*v1.Fip, error)
	Update(ctx context.Context, fip *v1.Fip, opts metav1.UpdateOptions) (*v1.Fip, error)
	UpdateStatus(ctx context.Context, fip *v1.Fip, opts metav1.UpdateOptions) (*v1.Fip, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Fip, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FipList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Fip, err error)
	FipExpansion
}

// fips implements FipInterface
type fips struct {
	client rest.Interface
}

// newFips returns a Fips
func newFips(c *KubeovnV1Client) *fips {
	return &fips{
		client: c.RESTClient(),
	}
}

// Get takes name of the fip, and returns the corresponding fip object, and an error if there is any.
func (c *fips) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Fip, err error) {
	result = &v1.Fip{}
	err = c.client.Get().
		Resource("fips").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Fips that match those selectors.
func (c *fips) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FipList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FipList{}
	err = c.client.Get().
		Resource("fips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fips.
func (c *fips) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("fips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a fip and creates it.  Returns the server's representation of the fip, and an error, if there is any.
func (c *fips) Create(ctx context.Context, fip *v1.Fip, opts metav1.CreateOptions) (result *v1.Fip, err error) {
	result = &v1.Fip{}
	err = c.client.Post().
		Resource("fips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fip).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a fip and updates it. Returns the server's representation of the fip, and an error, if there is any.
func (c *fips) Update(ctx context.Context, fip *v1.Fip, opts metav1.UpdateOptions) (result *v1.Fip, err error) {
	result = &v1.Fip{}
	err = c.client.Put().
		Resource("fips").
		Name(fip.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fip).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *fips) UpdateStatus(ctx context.Context, fip *v1.Fip, opts metav1.UpdateOptions) (result *v1.Fip, err error) {
	result = &v1.Fip{}
	err = c.client.Put().
		Resource("fips").
		Name(fip.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fip).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the fip and deletes it. Returns an error if one occurs.
func (c *fips) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("fips").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fips) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("fips").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched fip.
func (c *fips) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Fip, err error) {
	result = &v1.Fip{}
	err = c.client.Patch(pt).
		Resource("fips").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
