---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ports.neutron.io
spec:
  group: neutron.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: IP
        type: string
        jsonPath: .status.ip
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                id:
                  type: string
                ip:
                  type: string
                mac:
                  type: string
                securityGroupId:
                  type: array
                  items:
                    type: string
                cidr:
                  type: string
                gateway:
                  type: string
                mtu:
                  type: integer
                hostId:
                  type: string
                bindPod:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastUpdateTime:
                        type: string
                      lastTransitionTime:
                        type: string
            spec:
              type: object
              properties:
                name:
                  type: string
                projectId:
                  type: string
                networkId:
                  type: string
                subnetId:
                  type: string
                securityGroupId:
                  type: array
                  items:
                    type: string
                fixIp:
                  type: string
                fixMac:
                  type: string
                deleteByPod:
                  type: boolean
  scope: Namespaced
  names:
    plural: ports
    singular: port
    kind: Port
    shortNames:
      - port
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fips.neutron.io
spec:
  group: neutron.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: ExternalNetworkName
        type: string
        jsonPath: .spec.externalNetworkName
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                neutronRouters:
                  type: array
                  items:
                    type: object
                    properties:
                      neutronRouterID:
                        type: string
                      neutronRouterName:
                        type: string
                      availabilityZone:
                        type: string
                      externalGatewayIP:
                        type: string
                      subnets:
                        type: array
                        items:
                          type: string
                allocatedIPs:
                  type: array
                  items:
                    type: object
                    properties:
                      ip:
                        type: string
                      type:
                        type: string
                      resources:
                        type: array
                        items:
                          type: string
                forbiddenIPs:
                  type: array
                  items:
                    type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastUpdateTime:
                        type: string
                      lastTransitionTime:
                        type: string
            spec:
              type: object
              properties:
                description:
                  type: string
                externalNetworkID:
                  type: string
                externalNetworkName:
                  type: string
                allocationPools:
                  type: array
                  items:
                    type: object
                    properties:
                      cidr:
                        type: string
                      start:
                        type: string
                      end:
                        type: string
  scope: Cluster
  names:
    plural: fips
    singular: fip
    kind: Fip
    shortNames:
      - fip
