apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ports.neutron.io
spec:
  group: neutron.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Name
        type: string
        jsonPath: .spec.name
      - name: NetworkID
        type: string
        jsonPath: .spec.networkId
      - name: SubnetID
        type: string
        jsonPath: .spec.subnetId
      - name: SecurityGroupID
        type: string
        jsonPath: .spec.securityGroupId
      - name: IP
        type: string
        jsonPath: .spec.ip
      - name: gateway
        type: string
        jsonPath: .status.gateway
      - name: CIDR
        type: string
        jsonPath: .status.cidr
      - name: MAC
        type: string
        jsonPath: .spec.mac
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                id:
                  type: string
                cidr:
                  type: string
                gateway:
                  type: string
                mtu:
                  type: integer
                hostId:
                  type: string
                bindPod:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastUpdateTime:
                        type: string
                      lastTransitionTime:
                        type: string
            spec:
              type: object
              properties:
                name:
                  type: string
                networkId:
                  type: string
                subnetId:
                  type: string
                securityGroupId:
                  type: array
                  items:
                    type: string
                ip:
                  type: string
                mac:
                  type: string
  scope: Namespaced
  names:
    plural: ports
    singular: port
    kind: Port
    shortNames:
      - port
