apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ports.neutron.io
spec:
  group: neutron.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: IP
        type: string
        jsonPath: .status.ip
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                id:
                  type: string
                ip:
                  type: string
                mac:
                  type: string
                securityGroupId:
                  type: array
                  items:
                    type: string
                cidr:
                  type: string
                gateway:
                  type: string
                mtu:
                  type: integer
                hostId:
                  type: string
                bindPod:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastUpdateTime:
                        type: string
                      lastTransitionTime:
                        type: string
            spec:
              type: object
              properties:
                name:
                  type: string
                projectId:
                  type: string
                networkId:
                  type: string
                subnetId:
                  type: string
                securityGroupId:
                  type: array
                  items:
                    type: string
                fixIp:
                  type: string
                fixMac:
                  type: string
                deleteByPod:
                  type: boolean
  scope: Namespaced
  names:
    plural: ports
    singular: port
    kind: Port
    shortNames:
      - port
